### ISSUE TITLE
betticurve error

### ISSUE THREAD

**Issue by rohanaras** [Eetion/Eirene.jl#1]
I tried following along to the "Around the World" example. However, when I then tried to plot the betti curve of the same dataset, I got the following error: 
![image](https://user-images.githubusercontent.com/10246811/40251828-491b8b14-5a8f-11e8-83a3-756bfaf578a1.png)
Any idea as to why this is happening?

**Comment by henselman-petrusek** [comment]
Thanks for flagging!  We fixed the issue (an internal indexing system changed in the last release, and the updates hadn't completely trickled down to the betticurve function), and the new release should be out in the next week or so.  Please keep the comments coming!

**Comment by henselman-petrusek** [comment]
Patch released.  The most recent version of the package can now be acquired either by running `Pkg.clone` or waiting for the new release to be committed on metadata.jl (hopefully a few days).  After that, the update will install automatically next time the user runs `Pkg.update()`.  Please let us know if this doesn't resolve the issue!
