### ISSUE TITLE
Is this library actively maintained?

### ISSUE THREAD

**Issue by 00krishna** [Eetion/Eirene.jl#36]
Hello. I love the idea of doing computational topology in Julia. I was just wondering if this library is actively maintained? The last commit was in March 2020, so more than a year ago. If there is a different library that everyone is using, would you mind adding a comment below. Thanks.

**Comment by henselman-petrusek** [comment]
Hello!  Yes, it's maintained (albeit rather slowly).  There are also changes and updates planned for the future.  Happy to answer questions about any features, if you have questions.

**Comment by 00krishna** [comment]
Oh that is excellent. @Eetion . I appreciate your getting back to me. Yeah, julia is such an easier language to work without compromising speed. I am looking forward to the upcoming new features.

**Comment by henselman-petrusek** [comment]
Thanks!  Always happy to hear about feature requests or proposed extensions, also!
