### ISSUE TITLE
wasserstein_distance is not symmetric

### ISSUE THREAD

**Issue by dbhaskar92** [Eetion/Eirene.jl#43]
Output of optimized code (commit  [a214726](https://github.com/Eetion/Eirene.jl/tree/a2147264ff118b043cceeabc564af3dde4141233) onwards) depends on the order of arguments. To reproduce:

1) Generate data:

        julia> using Random
        julia> using Eirene
        julia> Random.seed!(123);
        julia> rescale(coords) = (coords .- maximum(coords))./(maximum(coords)-minimum(coords))
        julia> pt_cloud_1 = rescale(noisytorus(m=30, n=10));
        julia> pt_cloud_1[:,1]
        3-element Vector{Float64}:
         -0.027817932268719984
         -0.39172231301472105
         -0.454187098172808
        julia> pt_cloud_2 = rescale(noisycircle3());
        julia> pt_cloud_2[:,1]
        3-element Vector{Float64}:
         -0.0005529205231942241
         -0.5368438485462651
         -0.5630209048408695

2) Compute barcodes:

        julia> pers_diag_1 = eirene(pt_cloud_1, model="pc", maxdim=1);
        julia> pers_diag_2 = eirene(pt_cloud_2, model="pc", maxdim=1);
        julia> barcode_1_H1 = barcode(pers_diag_1, dim=1);
        julia> barcode_2_H1 = barcode(pers_diag_2, dim=1);

3) Print Wasserstein distances:

- On  [b38f8af](https://github.com/Eetion/Eirene.jl/tree/b38f8afb081e952f531fec50629b984bb0309bd5) (unoptimized version, note added by me)

        julia> wasserstein_distance(barcode_1_H1, barcode_2_H1, p=2, q=2)
        0.2104378587521066
        
        julia> wasserstein_distance(barcode_2_H1, barcode_1_H1, p=2, q=2)
        0.2104378587521066  (NOTE: same as above) 

- On  [a214726](https://github.com/Eetion/Eirene.jl/commit/a2147264ff118b043cceeabc564af3dde4141233)

        julia> wasserstein_distance(barcode_1_H1, barcode_2_H1, p=2, q=2)
        0.161803319206841
        
        julia> wasserstein_distance(barcode_2_H1, barcode_1_H1, p=2, q=2)
        0.11576837169320067  (NOTE: different from above)

- On master

      julia> wasserstein_distance(barcode_1_H1, barcode_2_H1, p=2, q=2)
      0.161803319206841
      
      julia> wasserstein_distance(barcode_2_H1, barcode_1_H1, p=2, q=2)
      0.11576837169320067 (NOTE: different from above, same as commit a214726)

Testing with other datasets, I found that `W(X,Y)` is close to `W(Y,X)` in commit  b38f8af or earlier , but significantly different in later versions. 

Can you please help me understand the discrepancy? I'm running Julia 1.6.2, happy to assist in testing/debugging the code :)

**Comment by henselman-petrusek** [comment]
Thanks for the report!  I'll defer to the Wasserstein authority on this.

**Comment by yossibokorbleile** [comment]
Jumping on to @Eetion thanks, thanks for the report! I have had a look, and think I have managed to localise the issue (without knowing exactly what caused it yet), and have a beta fix. @dbhaskar92 if you are happy to test it, I can provide you with the (stripped back) fix.

**Comment by yossibokorbleile** [comment]
If you look at my fork and commit  [434e891](https://github.com/yossibokor/Eirene.jl/commit/434e891d3678cd1512f04ce19133bf031e954292) it should be resolved.
Edited 15/09/2021: changed the commit reference above as there was an extra 's' at the bottom of the file in the previous commit.

**Comment by yossibokorbleile** [comment]
hey @dbhaskar92 just hoping to give this a bump and see if you have continued to encounter issues.

**Comment by dbhaskar92** [comment]
@yossibokor No, I did not encounter any further issues in commit 434e891, thanks so much!

**Comment by yossibokorbleile** [comment]
Great! Then we can close the issue @Eetion
