### ISSUE TITLE
How to format input distance matrix when there is no path and therefore no distance between 2 nodes?

### ISSUE THREAD

**Issue by MariaBras** [Eetion/Eirene.jl#44]
I am using a distance matrix, recorded as a .csv file, as input; I've tried just leaving the "cell" empty but that led to an error. I tried to find an example, either in the examples folder or online, but with no success. 
Thank you!

**Comment by yossibokorbleile** [comment]
Hi @MariaBras what is the underlying structure you are important? Is it a finite point cloud, or a complex?

**Comment by MariaBras** [comment]
Hi @yossibokor thanks for replying! It's a graph/network, in the form of a distance matrix.

**Comment by yossibokorbleile** [comment]
No problem, @MariaBras.  

So that we are all on the same page, could you describe what exactly you want to calculate using this distance matrix? 

It might be better to 'convert' the distance matrix in a complex, and go from there.

**Comment by MariaBras** [comment]
Hi @yossibokor 
At this point, I'm just trying to make the barcode and persistence diagrams. 
It sounds like knowing how to do the 'conversion' could be helpful later regardless?

**Comment by yossibokorbleile** [comment]
@MariaBras what is the object you are studying the persistence of?

**Comment by MariaBras** [comment]
@yossibokor It's a social network, with edges representing collaborations between the agents (nodes).

**Comment by yossibokorbleile** [comment]
@MariaBras what is the parameter you are taking persistence over? Are you selecting a parent node and then looking at all other nodes within distance $d$, or are you looking at adding in edges between nodes which are less than distance $d$ apart?

**Comment by MariaBras** [comment]
@yossibokor the latter, adding in edges between nodes which are less than distance _d_ apart.

**Comment by yossibokorbleile** [comment]
@MariaBras then you should create a filtered complex and use that as the input for Eirene. Happy to discuss how to do this, but the documentation is a good place to start.

**Comment by MariaBras** [comment]
@yossibokor Hi! Thank you again for taking the time to help me!
Just to clarify, there isn't a specific method written for this, it's something I'd code myself?
I've not been able to find anything relevant to this type of conversion on the internet yet, so if you have anywhere you could point me to, it would be v appreciated. :)

**Comment by yossibokorbleile** [comment]
@MariaBras there is no functionality for this in Eirene. But I am happy to help you through this. Probably best to move off this issue thread, so just send me an email and we can go from there.
