### ISSUE TITLE
Julia 1.7

### ISSUE THREAD

**Issue by wardjm** [Eetion/Eirene.jl#47]
I'm not sure what the dependency issue is, but I can't get this to install in Julia 1.7. I've added all the mentioned packages listed below:

(@v1.7) pkg> add Eirene
    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package CategoricalArrays [324d7699]:
 CategoricalArrays [324d7699] log:
 ├─possible versions are: 0.3.11-0.10.6 or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions 0.3.11-0.10.6
 ├─restricted by compatibility requirements with OutlierDetectionInterface [1722ece6] to versions: 0.10.0-0.10.6
 │ └─OutlierDetectionInterface [1722ece6] log:
 │   ├─possible versions are: 0.1.0-0.1.8 or uninstalled
 │   └─restricted to versions * by an explicit requirement, leaving only versions 0.1.0-0.1.8
 └─restricted by compatibility requirements with CSV [336ed68f] to versions: 0.3.11-0.8.3 — no versions left
   └─CSV [336ed68f] log:
     ├─possible versions are: 0.3.0-0.10.4 or uninstalled
     ├─restricted to versions * by an explicit requirement, leaving only versions 0.3.0-0.10.4
     └─restricted by compatibility requirements with Eirene [9c0f25c4] to versions: 0.3.0-0.7.10
       └─Eirene [9c0f25c4] log:
         ├─possible versions are: 1.0.0-1.3.6 or uninstalled
         └─restricted to versions * by an explicit requirement, leaving only versions 1.0.0-1.3.6

**Comment by yossibokorbleile** [comment]
Hey @wardjm 

I can't remember exactly what package caused this, but from memory there are some version dependency issues in other packages. I suggest you use Julia 1.6, unless it is absolutely necessary to use 1.7.
